<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Expert_Add_File_Image</name>
   <tag></tag>
   <elementGuidId>30681b50-ccb8-40c4-9923-6af1ecf09e58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1559286681469</value>
   </webElementProperties>
</WebElementEntity>
