<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Expert_Add_Btn_Commit</name>
   <tag></tag>
   <elementGuidId>d5b18179-406f-4b2d-8af7-2e74dcbf4c75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/section[contains(text(),'确定')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1559286961631</value>
   </webElementProperties>
</WebElementEntity>
