<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Expert_Add_Click_Domain</name>
   <tag></tag>
   <elementGuidId>828213a9-b3b7-4985-a425-d5fc640dcd74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[contains(text(),'选择领域')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1559286553141</value>
   </webElementProperties>
</WebElementEntity>
