<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dashboard_Appoinment</name>
   <tag></tag>
   <elementGuidId>48aa6252-d630-4287-96c4-b1d63d9d3179</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/li[text()='预约记录']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1559285301991</value>
   </webElementProperties>
</WebElementEntity>
